// >    MAIOR
// <    MENOR
// >=   MAIOR OU IGUAL
// <=   MENOR OU IGUAL
// ==   IGUAL A
// ===  IGUAL OU DO MESMO TIPO
// !=   DIFERENTE DE
// !==  DIFERENTE, INCLUSIVE DO TIPo

// &&   "E" AS DUAS CONDIÇÕES DEVEM SER VERDADEIRAS
//      PARA QUE A CONDIÇÃO FINAL SEJA TRUE (VERDADEIRA)

// ||   "OU" UMA DAS CONDIÇÕES DEVE SER VERDADEIRA
//      PARA QUE A CONDIÇÃO FINAL SEJA VERDADEIRA (TRUE)

// !    "NÃO" NEGA A CONDIÇÃO ATUAL. (SE FOR VERDADEIRA, FICA FALSA E VICE E VERSA)